### ISSUE TITLE
[Proposal] Fork Distribution under oras-project to support artifacts working group

### ISSUE THREAD

**Issue by sajayantony** [oras-project/artifacts-spec#10]
The proposal here is to have a fork of distribution under the ORAS project at https://github.com/oras-project/distribution . This will enable the ORAS working group to iterate over the artifact spec and provide a reference implementation PR for distribution which enables APIs like the referrers API that is a part of this proposal. 

Currently these changes are being presented under https://github.com/notaryproject/distribution/tree/reference-types and given that the API is meant to support more than signatures it makes sense to iterate and release these under this working group and stage these for upstream donation to the OCI and Distribution.

**Comment by SteveLasker** [comment]
This is a great example of investments in one project (Notary v2), incubating new, more generic ideas like Reference Types in the artifacts-spec. 
This would be within the scope of the artifacts-spec owners to add the fork here for incubation. 

LGTM

**Comment by SteveLasker** [comment]
https://github.com/oras-project/distribution

**Comment by justincormack** [comment]
LGTM
