### ISSUE TITLE
Question: Media type field required in artifact manifest?

### ISSUE THREAD

**Issue by michaelb990** [oras-project/artifacts-spec#100]
I believe it should be, but it currently reads differently than the other fields. The description of `mediaType` is:

> This field contains the mediaType of this document, differentiating from [image-manifest](https://github.com/opencontainers/image-spec/blob/master/manifest.md) and [image-index](https://github.com/opencontainers/image-spec/blob/master/image-index.md). The mediaType for this manifest type MUST be application/vnd.cncf.oras.artifact.manifest.v1+json, where the version WILL change to reflect newer versions.

vs e.g. `artifactType`

>The REQUIRED artifactType is a unique value, as registered with [iana.org](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md#registering-unique-types-with-iana). The artifactType values are equivalent to the values used in the manifest.config.mediaType in [OCI Artifacts](https://github.com/opencontainers/artifacts). Examples include sbom/example, application/vnd.cncf.notary.v2. For details on creating a unique artifactType, see [OCI Artifact Authors Guidance](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md)

The OCI image manifest & image index specs both require manifest media type to be present and I believe the artifact manifest should also require this field. If that opinion is shared by others, I will submit a PR to add a `REQUIRED` note to the description of the `mediaType` field in the artifact manifest.

Thanks!

**Comment by SteveLasker** [comment]
That makes sense, thanks @michaelb990

**Comment by sajayantony** [comment]
+1 it should be `REQUIRED` given the previous issues of this not being present.
