### ISSUE TITLE
Doc error: OCI image manifest listed as an example of artifact manifest

### ISSUE THREAD

**Issue by m5i-work** [oras-project/artifacts-spec#104]
An OCI image manifest is not a valid artifact manifest. But it's listed in [Example ORAS Artifact Manifests](https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md#example-oras-artifact-manifests) (the first item).

@SteveLasker @shizhMSFT Should we reference [this file](https://github.com/oras-project/artifacts-spec/blob/main/examples/oci-image-artifact.json) instead?

**Comment by SteveLasker** [comment]
Thanks @m5i-work. This is a good clarification. 
I didn't mean to imply the OCI Image is an ORAS Artifact manifest type. I just created an example for comparison, and then just listed each one. 
See PR #107
