### ISSUE TITLE
Discovery API Response Name Mismatch

### ISSUE THREAD

**Issue by akashsinghal** [oras-project/artifacts-spec#105]
The artifact spec defines the response to the discover API [here](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#api-discovery):

```http
200 OK
Content-Length: <length>
Content-Type: application/json

{
    "extensions": [
        {
            "name": "cncf.oras.referrers",
            "url": "https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md",
            "description": "ORAS referrers listing API",
            "endpoints": [
              "_oras/artifacts/referrers"
            ]
        }
    ]
}
```

The name of the oras extension is defined to be `cncf.oras.referres` in the artifact-spec. However, this violates the naming extension defined in the distribution spec for extensions [here](https://github.com/opencontainers/distribution-spec/blob/main/extensions/_oci.md#extensions-property-descriptions). 

The response to the discover API should be:

```http
200 OK
Content-Length: <length>
Content-Type: application/json

{
    "extensions": [
        {
            "name": "_oras",
            "url": "https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md",
            "description": "ORAS referrers listing API",
            "endpoints": [
              "_oras/artifacts/referrers"
            ]
        }
    ]
}
```

**Comment by sajayantony** [comment]
+1 Looks like I put in the incorrect value for the name.
