### ISSUE TITLE
Release 1.0.0-rc.2

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/artifacts-spec#110]
Proposing we release artifacts-spec-1.0.0-rc.2

> Based on feedback and discussions with [@michaelb990](https://github.com/michaelb990), I’ve updated the wording here:

[rc.2](https://github.com/oras-project/artifacts-spec/milestone/5) provides projects [consuming the ORAS artifacts-spec](https://github.com/oras-project/artifacts-spec#project-status) an updated tag to develop against.

In the meantime, we continue to actively participate in the [OCI Reference Type Working Group](https://github.com/opencontainers/wg-reference-types/). We hope to be able to migrate to an OCI-supported solution before releasing 1.0.0.

High-level deliverables as follows:

- [x] Decide on main commit for release - https://github.com/oras-project/artifacts-spec/commit/eddd1d8790c9ff4cfd0db4b76f47a06f86599b06
- [x] Cut branch named [`v1.0.0-rc.2`](https://github.com/oras-project/artifacts-spec/tree/v1.0.0-rc.2) based on agreed upon main commit
- [x] Cut a tag named [`v1.0.0-rc.2`](https://github.com/oras-project/artifacts-spec/tree/v1.0.0-rc.2)
- [x] Cut a release named [`v1.0.0-rc.2`](https://github.com/oras-project/artifacts-spec/releases/tag/v1.0.0-rc.2)

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release?

**Comment by sajayantony** [comment]
LGTM

**Comment by dtzar** [comment]
LGTM.  Release would be what's on main branch right now.  Maybe I'm missing it, but it doesn't look like there are any specific versions/links which need to be updated in the readme.

**Comment by jdolitsky** [comment]
> This also gives us a chance to evaluate the output of the [OCI Reference Type Working Group](https://github.com/opencontainers/wg-reference-types/) progress before releasing 1.0.0.

Could you elaborate here? Several people involved in this project are maintainers in the WG, so it seems like you should know exactly the status of that effort.

For those not involved, the WG has converged on a direction that is fairly similar to this spec.

So you should all know that pushing this effort forward at this point will only serve to fragment the OCI ecosystem and sow distrust and confusion, which would really be just absolutely terrible timing considering we're all finally working together.

**Comment by michaelb990** [comment]
@jdolitsky thanks for the feedback. Hopefully, nobody really believes there's a conspiracy to sow distrust and confusion here... :) The work that's been done in this repo, as I'm sure many are aware, was

**Comment by michaelb990** [comment]
@jdolitsky Thanks for the feedback! I don't think that anyone's trying to sow distrust and confusion, so hopefully the updates help to clarify that. 

I'm excited to continue participating in the working group, as are many others in this project, to get to a final proposal and bring it back to the OCI. This RC2 tag will be helpful to other projects who continue to iterate on solutions for references, but it's my hope we'll be able to move towards the output of the OCI WG when we have finalized it 👍

**Comment by michaelb990** [comment]
LGTM.

**Comment by SteveLasker** [comment]
Proposing commit: https://github.com/oras-project/artifacts-spec/commit/eddd1d8790c9ff4cfd0db4b76f47a06f86599b06 as the version the LGTMs were assocaited with.

**Comment by SteveLasker** [comment]
Completed, congrats on the excellent continued progress.
