### ISSUE TITLE
Provide a Q&A to explain the ORAS Artifact Spec status and relationship with OCI artifact spec

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/artifacts-spec#118]
We see more and more people confused about the project status and relations with OCI artifact spec, like https://github.com/oras-project/artifacts-spec/issues/117
 and 
https://cloud-native.slack.com/archives/C02AJS1BUTX/p1665691786144209

@michaelb990 @oras-project/oras-artifacts-spec-maintainers  Let's create a Q&A list to explain the project status and relationship with OCI spec in this repo. I will draft a doc first and request your review.

**Comment by michaelb990** [comment]
@FeynmanZhou any updates on this? I don't think we need to overthink this. A short note on the README and an archive status on the repo (a la https://github.com/opencontainers/wg-reference-types) would help to clear up confusion.
