### ISSUE TITLE
Create go specs for other projects like distribution to consume

### ISSUE THREAD

**Issue by sajayantony** [oras-project/artifacts-spec#15]
We have the media type defined under https://github.com/notaryproject/artifacts and this should move into the artifact specs similar to https://github.com/opencontainers/image-spec/tree/main/specs-go

We can move the the following specs `https://github.com/aviral26/artifacts/tree/prototype-3/specs-go/v2` so that oras-project/distribution#2

**Comment by SteveLasker** [comment]
Closing, per #17
