### ISSUE TITLE
Why do we define Lifecycle Management in the artifact-spec?

### ISSUE THREAD

**Issue by lahirurd** [oras-project/artifacts-spec#20]
I think it is unnecessary because:

1. Manifest spec defines what the manifest is. Lifecycle management is about object storage, and seems out-of-place in a manifest spec. Current OCI manifest specs don’t define lifecycle management.
2. Differences in lifecycle management between registries does not affect cross-registry portability of artifacts. Therefore there is no immediate need for everyone to agree on one particular behavior.
3. Registries currently implement object cleanup based on their own use-cases (public vs private, free vs paid). Adding a requirement in the spec will force all registries to adopt the same behavior for reference artifacts, which may be inconsistent with their current object cleanup behavior.

I do agree that the spec should not prevent registries managing object lifecycles efficiently. Preventing reference cycles that could occur due to the reverse-ownership relation introduced by the `subjectManifest` field is important in this regard. 

Therefore I propose that we remove the “Lifecycle Management” section from `artifact-manifest.md`, and instead document that preventing reference cycles was a goal when designing this spec.

**Comment by SteveLasker** [comment]
Thanks @lahirurd,
This is a great discussion. With the addition of references and the many inconsistencies with registries, the intent here is to help standardize expectations across registries. Over the last several years, we've all seen registries grow in size, and users struggle to maintain the content within their registries, differentiating the content they've deployed vs. just built. Reverse references adds the risk of dangling documents if not specified.

With the `artifact.manifest` being a new document that describes the relationships between artifacts, it seemed like the right time to start setting consistent expectations. 


Is there something in conflict to ecr behavior?

I believe these are the relevant sections:

> [Lifecycle management defined](https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md#oras-artifact-and-image-spec-differences), starting to provide standard expectations for how users can manage their content. It doesn't define GC as an internal detail

> ## [Lifecycle Management](https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md#lifecycle-management)
> For Phase 1, artifact types will be limited to reference types. A reference type is an artifact that doesn't have a lifecycle unto itself. A container image is said to have an independent lifecycle. A reference type, such as an SBoM or signature have a lifecycle tied to the subjectManifest. When the subjectManifest is deleted or marked for garbage collection, the defined artifact is subject to deletion as well. A distribution instance SHOULD delete, (refCount -1) the artifact when the subjectManifest is deleted.

**Comment by lahirurd** [comment]
I don't think there's anything specific to ECR that's the issue here. ECR does not delete untagged images by default, and based on [this](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-tag-version#delete-untagged-manifests) neither does ACR?

My concern here is that we're defining an artifact manifest here, and not just a "reference type". `subjectManifest` is defined to be optional field. Therefore if we push an artifact _without_ a `subjectManifest`, how would its lifecycle look like? Would this artifact have a lifecycle on its own? Does the presence of the `subjectManifest` field control the lifecycle of an artifact then, and an artifact with a `subjectManifest` is "less permanent" than one without?

Perhaps some users might _want_ to keep artifacts around even after their `subjectManifest` is deleted. `subjectManifest` relationship is not a parent-child relationship after all. Not defining the behavior in the spec allows registries to choose the behavior they want, based on their users' needs.

**Comment by dlorenc** [comment]
For whatever it's worth, I'm a maintainer of the cosign image signing tool. We use a workaround today with tags to ensure signatures do not get prematurely garbage-collected, which has the end result of signatures **never** getting garbage collected, even if the image they refer to is manually deleted.

I initially expected lots of pushback to this behavior, but I've received literally zero complaints from end users. Cosign is currently in use at scale, in production, by several dozen organizations.

**Comment by sudo-bmitch** [comment]
I think OCI should work on defining a common expectation for lifecycle management, but that's not something that belongs in artifact-spec, rather it should be done in distribution-spec. I disagree that we should expect every registry to make their own choices, because the result is very inconsistent behavior for users and any tooling or workflow designed to work with a user's choice of registries becomes brittle and error-prone.

As long as the created artifacts can be cleaned by a GC policy on most registries, we should be fine leaving this out of artifact-spec. The two requirements I see are:
- Existing registries without artifact-spec support shouldn't break if they have artifacts pushed (no 5xx errors) and artifacts shouldn't be impossible to GC.
- Registries that add support for artifact-spec shouldn't be expected to implement a major redesign of their GC policies (e.g. to handle reference loops).

To @dlorenc's point, tagging an artifact can also be used to alter the lifecycle policy, but I'd like to know that solutions are possible that do not depend on this.

**Comment by dlorenc** [comment]
+1, I like that framing of the requirements!

**Comment by lahirurd** [comment]
I agree. If/when lifecycle management is added to an OCI spec, it should consider all types of manifests, and clearly define how it should work for all use-cases. It's non-trivial work, and I don't think we should/need to do it here/now.

**Comment by michaelb990** [comment]
Fixed by #31.
