### ISSUE TITLE
Artifact descriptor should be a superset of the v1.0.1 image-spec descriptor

### ISSUE THREAD

**Issue by aviral26** [oras-project/artifacts-spec#21]
Currently, the artifact descriptor does not define some properties that exist in the image-spec [v1.0.1 descriptor](https://github.com/opencontainers/image-spec/blob/d60099175f88c47cd379c4738d158884749ed235/descriptor.md), namely:

*  `urls`
*  `annotations`
*  `data` (reserved field)

Any client authoring an ORAS Artifact Manifest should be able to use these properties in the `subjectManifest` or `blobs` objects.

The artifact descriptor [spec](https://github.com/oras-project/artifacts-spec/blob/main/descriptor.md) should be updated to include these additional properties.

**Comment by SteveLasker** [comment]
urls and annotations were mistakenly removed when the lifting of annotations into the descriptor was reverted.

**Comment by sajayantony** [comment]
`platform` struct is also missing here https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/descriptor.go#L45
