### ISSUE TITLE
Confusing language around reference type(s)

### ISSUE THREAD

**Issue by mikebrow** [oras-project/artifacts-spec#24]
From the [artifactmanifest.md](https://github.com/oras-project/artifacts-spec/blob/6c8545ffd4217f7ece44c449b50beeba3e667351/artifact-manifest.md) doc I had some questions/clarification recommendations 

The doc says phase one reference types.. but does not define reference types.. rather at the bottom of the doc I see that "A reference type is an artifact that doesn't have a lifecycle unto itself." Given that the subjectManifest is "optional" that does not jibe with this statement.  I'd put the "is a" definition up top.. then later on here you can say something like when subjectManifest is present.. 

I think you are saying new base artifact focused media types like a new manifest.

if so maybe update the doc to add that specific clarity. 

In the sentence `an artifact manifest provides an optional collection of blobs and a reference to the manifest of another artifact.`  I think you mean something like "an artifact manifest provides an optional collection references to objects (called `blobs`) that have information/content associated with this manifest/object; and also an optional reference (called `subjectManifest`) that points to a manifest for which this artifact (manifest) is dependent."

------
In the following paragraph there are some issues. 
``` 
Tagged referenceTypes

As signatures and SBoMs are not considered independent artifact types, they SHOULD NOT have a tag, simplifying the lifecycle management. As the subjectManifest is marked for deletion (refCount=0), the referenctType is also marked for deletion (refCount -1). However, these artifacts MAY have tags as future versions of the artifact manifest MAY support independent types.
```
typo: `referenctType`

I think you mean something like both the object referred to by the subjectManifest and all artifact manifest objects referring to the subject manifest object MUST have the same lifecycle (be marked for deletion along with the subject manifest object..

Looking over at the [artifact descriptor definition](https://github.com/oras-project/artifacts-spec/blob/6c8545ffd4217f7ece44c449b50beeba3e667351/descriptor.md) 
```
artifactType string

This OPTIONAL property defines the type or Artifact, differentiating artifacts that use the application/vnd.oras.manifest. When the descriptor is used for blobs, this property MUST be empty.
```
Suggest "This OPTIONAL property defines the (media) type of this artifact descriptor."

I don't understand the context switch to the following text "differentiating artifacts that use the application/vnd.oras.manifest. When the descriptor is used for blobs, this property MUST be empty."

In the example at the bottom:
```json,title=Content%20Descriptor&mediatype=application/vnd.oci.descriptor.v1%2Bjson
{
  "mediaType": "application/vnd.cncf.oras.artifact.manifest.v1+json",
  "digest": "sha256:5b0bcabd1ed22e9fb1310cf6c2dec7cdef19f0ad69efa1f392e94a4333501270",
  "size": 7682,
  "artifactType": "org.cncf.notary.v2"
}
```
the text "cncf.notary.v2 signature" and ""org.cncf.notary.v2" don't seem to jibe.. or are confusing

**Comment by mikebrow** [comment]
in general it is a bit confusing where fields are the same / copied from the image spec.. hard to find what is new different from the image spec in these large descriptions.. maybe italics where it is the same or some bolding or asterisks could be used where it is different?

**Comment by SteveLasker** [comment]
Thanks Mike for the great feedback and clarity.
I've done an update to the markdown files in #36 
Please take a look when you get a chance.

**Comment by lachie83** [comment]
Preemptively closing as PR has been merge. Please reopen should you have further questions @mikebrow
