### ISSUE TITLE
/referrers API error codes & behavior

### ISSUE THREAD

**Issue by michaelb990** [oras-project/artifacts-spec#37]
Define error codes & behavior for the referrers API.

Most important questions in my mind:
* Should the `/referrers` API return results when the digest doesn't exist in the repository? (This seems like a possible scenario if an image is deleted but the reference artifacts aren't)
* Do we need any new error codes? Current list of codes are: [here](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes)

Anything I'm missing?

**Comment by dlorenc** [comment]
> * Should the `/referrers` API return results when the digest doesn't exist in the repository? (This seems like a possible scenario if an image is deleted but the reference artifacts aren't)

I think this would depend on whether the references are cleaned up. I'd prefer if it were still possible to retrieve references for an artifact that no longer exists.

A registry implementation could decide to clean these up and garbage collect them, or it could keep them around and still return them.

**Comment by lachie83** [comment]
@michaelb990 is going to review the current error codes and make any changes required for draft.1. The larger discussion regarding how to handle dangling references will be punted to draft.1
