### ISSUE TITLE
Release artifacts-spec-1.0.0-draft.1

### ISSUE THREAD

**Issue by lachie83** [oras-project/artifacts-spec#41]
Proposing we release artifacts-spec-1.0.0-DRAFT1 as we have completed the [milestone](https://github.com/oras-project/artifacts-spec/milestone/1). Release process is defined [here](https://github.com/oras-project/artifacts-spec/milestone/1).

High level deliverables as as follows:

- [x] Decide on main commit for release - https://github.com/oras-project/artifacts-spec/commit/eecc5d95bcee4741b8d28125e3817a456b76627d
- [x] Cut branch named `1.0.0-draft.1` based on agreed upon main commit
- [x] Cut a tag named `1.0.0-draft.1`
- [ ] Update README.md

/cc @SteveLasker @michaelb990 @justincormack @sajayantony 

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release.

**Comment by lachie83** [comment]
Will provide a release commit on the main branch once https://github.com/oras-project/artifacts-spec/pull/39 lands

**Comment by SteveLasker** [comment]
LGTM, +1

**Comment by sajayantony** [comment]
LGTM  once #39 is merged in.

**Comment by SteveLasker** [comment]
#39 is now merged, with a link fix as a result of #35.
[draf1](https://github.com/oras-project/artifacts-spec/milestone/1) candidate: https://github.com/oras-project/artifacts-spec/commit/c2172a9848af285bba6af2ca9c30a06515b008a9

**Comment by michaelb990** [comment]
+1

**Comment by shizhMSFT** [comment]
LGTM

**Comment by justincormack** [comment]
LGTM

**Comment by lachie83** [comment]
https://github.com/oras-project/artifacts-spec/pull/44 was added to the milestone and has been merged. 

DRAFT1 candidate commit - https://github.com/oras-project/artifacts-spec/commit/7948e176385a57e2d979165897bd248d59b549b4

**Comment by SteveLasker** [comment]
Updating with the latest commit for `draft.1`:  https://github.com/oras-project/artifacts-spec/commit/eecc5d95bcee4741b8d28125e3817a456b76627d

**Comment by SteveLasker** [comment]
agreed to cut a branch & tag named: `1.0.0-draft.1` after the milestone.

**Comment by SteveLasker** [comment]
[Draft 1](https://github.com/oras-project/artifacts-spec/releases/tag/1.0.0-draft.1) has been released: yay:
