### ISSUE TITLE
Incompatible go mod version

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/artifacts-spec#59]
As [golang documentation](https://golang.org/ref/mod#versions) states

> A version identifies an immutable snapshot of a module, which may be either a release or a pre-release. Each version starts with the letter v, followed by a semantic version. See Semantic Versioning 2.0.0 for details on how versions are formatted, interpreted, and compared.

In short, golang requires tags starting with the letter `v`. Therefore, it is suggested to have `v1.0.0-draft.1` instead of `1.0.0-draft.1`. Otherwise, `1.0.0-draft.1` will be resolved to a pseudo-version `v0.0.0-20210914235636-eecc5d95bcee`.

**Comment by sajayantony** [comment]
@michaelb990 @lachie83 @SteveLasker any concerns on this?

**Comment by SteveLasker** [comment]
makes sense, LGTM

**Comment by michaelb990** [comment]
this makes sense - thanks for bringing it up. let's retag the release?

**Comment by sajayantony** [comment]
@shizhMSFT - This shouldn't have been closed since I haven't yet tagged the release.

**Comment by sajayantony** [comment]
Closing this now since we now have https://github.com/oras-project/artifacts-spec/releases/tag/v1.0.0-draft.1
