### ISSUE TITLE
artifactType missing from example manifest

### ISSUE THREAD

**Issue by nelson-wu** [oras-project/artifacts-spec#61]
Shouldn't https://github.com/oras-project/artifacts-spec/blob/1.0.0-draft.1/examples/net-monitor-oci-image.json have the `artifactType` field?

**Comment by sajayantony** [comment]
@nelson-wu - that is oci-image and that schema doesn’t have the ‘artifactType’ which is only a part of the new manifest.

**Comment by nelson-wu** [comment]
I see, I was just confused since it's listed as an example artifact manifest here. Should we clarify this page? https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md

**Comment by sajayantony** [comment]
Maybe we should just point to the image-spec repo example. This repo also doesn’t contain the example for OCI index. So it’s not a full set. 
@SteveLasker what do you think?

**Comment by SteveLasker** [comment]
I was trying to keep a set of examples that we can point to within the docs, and not chase examples that may change outside of the repo.  This way we can show how an artifact-manifest can be used to sign an image-manifest, or an SBOM can be added to an image-manifest. I could add an OCI multi-arch Index and show how it signs that as well, if that's interesting.

**Comment by SteveLasker** [comment]
Thanks @nelson-wu for opening the issue. This looks to be resolved. Please activate if the response didn't address the question about examples.
