### ISSUE TITLE
Link to annotations.md is dead

### ISSUE THREAD

**Issue by nelson-wu** [oras-project/artifacts-spec#63]
On https://github.com/oras-project/artifacts-spec/blob/main/artifact-manifest.md there is a link which points towards https://github.com/oras-project/artifacts-spec/blob/main/annotations.md#rules which is currently a dead link.

**Comment by sajayantony** [comment]
Do you want to send a PR to fix it?

**Comment by nelson-wu** [comment]
I would; unfortunately I do not know of the whereabouts of this file in the repo, nor am I in possession of this file.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
