### ISSUE TITLE
Slight typo: `vnd.org.cncf....`

### ISSUE THREAD

**Issue by imjasonh** [oras-project/artifacts-spec#69]
In [filtering examples](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#filtering-results), you reference the artifact type `application/vnd.org.cncf.notary.v2`. I think you mean to use `application/vnd.cncf.notary.v2` (no `org.`), since this makes it seem like it's a reverse-domain-name scheme referring to [cncf.org](https://www.cncf.org/) which is unaffiliated with the CNCF (https://cncf.io).

This is moot if filtering is pinned for later (#68), or if specific example media types are removed (#66), but in case those don't come to pass, we should fix the typo.

**Comment by SteveLasker** [comment]
@imjasonh, thanks for the catch. We've had a number of changes to names. Please feel free to make the PR, or I can do some cleanup as part of #66

**Comment by SteveLasker** [comment]
Closing as a result of #71
