### ISSUE TITLE
Change root path for referrers to support distribution extensions proposal

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/artifacts-spec#74]
This tracks the changing of the [/referrers](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#api-path) API from `/oras/artifacts/v1/{repository}/manifests/{digest}/referrers` to the [OCI Distribution extension proposal #111](https://github.com/opencontainers/distribution-spec/pull/111)

**Comment by vbatts** [comment]
I for sure am curious how this example would translate into the `/v2/_<ns>/<ext>/<operation>[?<key>=<value>...]`  or `/v2/<name>/_<ns>/<ext>/<component>[?<key>=<value>&...]` layout 🤔

**Comment by vbatts** [comment]
I like the REST layout, but how to maintain an extendible structure that works for generic use-cases as well?

**Comment by SteveLasker** [comment]
Closing as this got merged in #87
