### ISSUE TITLE
Document artifactType formatting

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/artifacts-spec#8]
OCI Artifacts uses the `manifest.config.mediaType` to capture the unique artifact types.
This puts an additional burden to use iana.org mediaTypes, and longer formatting: `application/vnd.org.project.subproject.version+config-file-format` 
The OCI Artifact standard is captured in the [Artifact Authors](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md#defining-a-unique-artifact-type) content. 

For Artifact Manifest, we're decoupling from the `manifest.config.mediaType`, enabling optional config objects to be used/or shared across artifact types, while an artifact can declare it's helm, wasm, notary v2, spdx sbom, nydus, etc. 

For the `artifactType`, we've started using: `org.[org-name].project.version`. However, we haven't clarified the format in the artifact-manifest spec.

**Comment by jonjohnsonjr** [comment]
I would caution against inventing a new namespace, registry, or naming convention without good reason.

If you don't want to use media types, consider using [reverse domain notation](https://en.wikipedia.org/wiki/Reverse_domain_name_notation) (like OCI annotations keys), but media types are a pretty good fit for the `artifactType` field being proposed, IMO.

**Comment by SteveLasker** [comment]
> ...consider using reverse domain notation (like OCI annotations keys), but media types are a pretty good fit for the artifactType field being proposed, IMO.

This is good feedback. I had other feedback that we shouldn't use the more complex iana.org mediaTypes. 
As we document these, this is good feedback to consider in that PR.

**Comment by SteveLasker** [comment]
To keep things simple, we'll use the same iana.org mediaTypes used in oci artifacts.
