### ISSUE TITLE
Cut RC1

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/artifacts-spec#88]
Proposing we release artifacts-spec-1.0.0-rc.1
Account for [issues and PRs tagged RC1](https://github.com/oras-project/artifacts-spec/milestone/4)

High-level deliverables as follows:

- [x] Decide on main commit for release - [9ff738f](https://github.com/oras-project/artifacts-spec/commit/9ff738fa634c1995e4c0d447c027bc61f8e992d7)
- [x] Cut branch named `v1.0.0-rc.1` based on agreed upon main commit
- [x] Cut a tag named `v1.0.0-rc.1`
- [x] Update README.md

/cc @SteveLasker, @michaelb990, @justincormack, @sajayantony

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release.

**Comment by SteveLasker** [comment]
awaiting #92 and #94 to be merged

**Comment by SteveLasker** [comment]
All active PRs are now merged, identified [9ff738f](https://github.com/oras-project/artifacts-spec/commit/9ff738fa634c1995e4c0d447c027bc61f8e992d7) as the commit to cut `RC.1`

**Comment by michaelb990** [comment]
+1

**Comment by sajayantony** [comment]
+1 LGTM. @northtyphoon

**Comment by dlorenc** [comment]
Maybe a dumb question, but how is this spec intended to interact with the outcome from the [OCI Reference Types Working Group](https://github.com/opencontainers/wg-reference-types)? Is it intended to live side by side long-term, or will they merge?

**Comment by sajayantony** [comment]
@dlorenc  I think the ORAS project should evaluate the OCI Reference Type proposal once it has made it into Distribution, Image or Artifact Spec.

**Comment by sudo-bmitch** [comment]
That is disappointing. I had hoped that WG contributors would take a more active role in promoting the recommendations of the working group.

**Comment by michaelb990** [comment]
Hey @sudo-bmitch! Finalizing this RC is not intended to detract from the recommendations of the WG. Several of the maintainers of this project are active contributors and promoters of the WG, myself included. The WG discussions have informed this spec, and I intend to continue working on both. I don’t think it’s realistic for work outside the WG to halt, this is just a next step in work already in flight. If you want to talk more about this, feel free to ping me directly -- I’d like to keep this issue related to oras-project/artifacts-spec work.

**Comment by dlorenc** [comment]
> If you want to talk more about this, feel free to ping me directly -- I’d like to keep this issue related to oras-project/artifacts-spec work.

Thanks @michaelb990 , I'll create a new issue with more questions on the future plans here.
