### ISSUE TITLE
Manifest Referrers API: Pagination: Allow relative url for next link

### ISSUE THREAD

**Issue by northtyphoon** [oras-project/artifacts-spec#93]
> https://github.com/oras-project/artifacts-spec/blob/v1.0.0-draft.1/manifest-referrers-api.md#paging-results 

> If there are more items, the URL for the next collection is encoded in a [RFC5988](https://datatracker.ietf.org/doc/html/rfc5988) Link header, as a "next" relation. Clients SHOULD treat this as an opaque value and not try to construct it themselves.

In current v1.0.0-draft.1 spec, the next link in pagination result is an absolute url that the client will treat as an opaque value. The challenge of the requirement is the absolute url will not work if the registry is running behind a gateway/proxy. The following flow illustrates the problem. In this case, client is only able to connect to `myregistry.gateway.io`.

client => myregistry.gateway.io(gateway) => myregistry.azurecr.io (registry)

If the next link returned by the registry is an absolute path, eg, `http://myregistry.azurecr.io/oras/artifacts/v1/hello-world/manifests/sha256:3c3a4604a545cdc127456d94e421cd355bca5b528f4a9c1905b15da2eb4a4c6b/referrers?n=5&nextToken=abc`, the client won't be able to follow the link to request the next page items.

We propose to loose the constraint to allow relative path in the paging result. For the above example, the next link will be `/oras/artifacts/v1/hello-world/manifests/sha256:3c3a4604a545cdc127456d94e421cd355bca5b528f4a9c1905b15da2eb4a4c6b/referrers?n=5&nextToken=abc`. 
The client will parse the url and compose the full url with the appropriate host: `https://myregistry.gateway.io/oras/artifacts/v1/hello-world/manifests/sha256:3c3a4604a545cdc127456d94e421cd355bca5b528f4a9c1905b15da2eb4a4c6b/referrers?n=5&nextToken=abc`

**Comment by SteveLasker** [comment]
Thanks @northtyphoon,
Minor tweak as the path is referencing what was shipped in v1.0.0-draft.1, as opposed to the current path which incorporated the OCI extensibility

Here's the [current path](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#api-path)

```bash
GET /v2/{repository}/_oras/artifacts/referrers?digest={digest}

GET /v2/net-monitor/_oras/artifacts/referrers?digest=sha256:3c3a4604a545cdc127456d94e421cd355bca5b528f4a9c1905b15da2eb4a4c6b
```

I noticed the PR has the correct path, so it's just the summary here.
