### ISSUE TITLE
Future Plans and Interoperability With OCI Reference Types

### ISSUE THREAD

**Issue by dlorenc** [oras-project/artifacts-spec#96]
Moving the discussion from #88 over to here.

I'm curious what the future plans for this specification are, and how it is expected to interact with the work happening in the OCI Reference Types WG. A few questions:

Are both expected to be supported long term?

Is this an alternative to the work produced from the OCI, or an extension? What's the best way to think about how they're related?

Is there a difference in functionality? How should client tooling decide which to use?

I'm a bit worried this is going to lead to fragmentation of the OCI specifications and registry operators/clients will be forced to choose to support one or the other here. Even if registries support both, it could lead to a confusing story for end users and clients. Have there been any discussions or plans on how this will be surfaced to end users/clients?

**Comment by xiaods** [comment]
Personally, I feel that this is an experimental feature and still differs from the objectives of OCI. It would be great if it could lead to a new standard from a product library perspective. It would save the dependency on nexus or artifactory. Let's have a unified base component for application releases.

**Comment by jdolitsky** [comment]
Any further effort spent on this project should be redirected to the OCI Reference Types working group. Not doing so indicates a lack of trust and integrity for all persons involved in both.

**Comment by SteveLasker** [comment]
Closing as this was covered in: https://github.com/opencontainers/artifacts/pull/29

**Comment by sudo-bmitch** [comment]
@SteveLasker should we take that as confirmation that ORAS will continue to develop a competing spec to the OCI WG?

**Comment by jdolitsky** [comment]
> ORAS will continue to develop a competing spec to the OCI WG?

This is the only way I would interpret this.

If that is indeed is the case, I would like to say "not cool Steve"! We are very close to coming to agreements on new APIs in the WG.

**Comment by SteveLasker** [comment]
Please stop, this was all covered in https://github.com/opencontainers/artifacts/pull/29

**Comment by jdolitsky** [comment]
re-opening to gain clarification

**Comment by jdolitsky** [comment]
Reconsidering some of my words and actions here, and I apologize for any feelings of hostility.

I think people are genuinely confused how this project relates to the goals of the OCI efforts. I'm just hoping we can all work together, especially now that we have everyone in the room.
